language: python
python:
- '3.6.0'
install:
  - pip install pep8
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install autopep8
script:
  - python --version
  - python -m unittest discover -v
  - coverage run -m unittest discover
  - pep8 . | cut -d: -f1 | sort | uniq | xargs autopep8 -i
  - pep8 .
after_success:
  - coveralls
  - codeclimate-test-reporter
