language: python
python:
- '3.6.0'
install:
  # - pip install -r test-requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
script:
  - python --version
  - python -m unittest discover -v
  - coverage run -m unittest discover
  - pep8 .
after_success:
  - coveralls
  - codeclimate-test-reporter
